name: gestion_tareas_prueba_tecnica
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  path_provider: ^2.1.0
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  provider: ^6.1.5
  to_csv: ^5.0.4
  fluttertoast: ^8.1.1
  flutter_slidable: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
